baseURL = "https://rajorshi.net"
title = "Through The Stacks"
theme = "ananke"
publishDir = "docs"
disqusShortname = "ragebiswas"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[params]
  description = "Rajorshi's Blog"
  twitter = "https://twitter.com/rajorshi_biswas"
  github = "https://github.com/ragebiswas"
  linkedin = "https://www.linkedin.com/in/rajorshibiswas/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
