#baseURL = "http://www.rajorshi.net"
title = "Bits & Bytes"
theme = "ananke"
publishDir = "docs"

[params]
  description = "The last theme you'll ever need. Maybe."
  twitter = "https://twitter.com/rajorshi_biswas"
  github = "https://github.com/ragebiswas"
  linkedin = "https://www.linkedin.com/in/rajorshibiswas/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
